// Operator/placement traces — the executable side of GladeAuthzModel §7a/§7b
// and GladeWorkspaceDirectory §7b: node trust as the operator relation,
// placement as a granted verb, roaming through an entry node, and the
// directional exposure rule. INV-5 polices placement throughout.
import type { Scenario } from './types';
import { pick } from './actors';

const AZ = 'GladeAuthzModel';
const WD = 'GladeWorkspaceDirectory';

export const S_ROAM: Scenario = {
  id: 's-roam',
  stage: 2,
  title: 'Roaming — entry node, warm replica, blind pipe',
  summary: 'Away from the office: web-bootstrap to a DC entry node, directory from the operator-held replica, route home via iroh — and the café’s speed is a placement grant the owner controls.',

  actors: pick('gryth1', 'dc1', 'iroh', 'local1'),

  initial: {
    gryth1: { device: 'gianni’s laptop (device cert)', location: 'café wifi' },
    dc1: {
      operator: 'saas-corp',
      'replica home': 'synced (durable home-node role)',
      'hold home': 'granted: saas-corp (by gianni, at signup)',
      'hold ws-razel': 'granted: gianni, saas-corp',
      trust: 'plug: device certs + corp OIDC (per gianni’s authn policy)',
      'grant gryth1 ws-razel': 'read.*, gwz.* (replicated)',
      'grant gryth1 ws-secret': 'owner (all verbs, replicated)',
      'sub home': 'local1 (mesh)',
    },
    local1: {
      operator: 'gianni',
      'claim ws-razel': 'held — epoch 2',
      serving: 'ws-razel via grazel',
      'replica ws-razel': 'origin',
      'hold ws-razel': 'granted: gianni, saas-corp',
      'claim ws-secret': 'held — epoch 1',
      'replica ws-secret': 'origin',
      'hold ws-secret': 'granted: gianni ONLY',
      'grant gryth1 ws-secret': 'owner (all verbs)',
    },
  },

  phases: [
    { id: 'RM1', label: 'Walk in the door', summary: 'Web bootstrap + HELLO at the entry node; interactive auth happens exactly once.' },
    { id: 'RM2', label: 'Directory at the operator replica', summary: 'The list renders before any p2p — the DC fleet already holds the home share.' },
    { id: 'RM3', label: 'Route home (warm replica)', summary: 'ServeClaim → iroh → relay dial; placement grant makes dc1 a warm replica.' },
    { id: 'RM4', label: 'Blind pipe (owner’s policy)', summary: 'The sensitive share refuses placement — reads still work, riding home every time.' },
  ],

  steps: [
    {
      state: 'A1', phase: 'RM1', kind: 'message', from: 'gryth1', to: 'dc1', frame: 'HELLO',
      label: 'session at the entry node',
      payload: { detail: { bootstrap: 'DNS + wss to the fleet (before glade)', session: 'sess-cafe1', deviceCert: 'valid — chains to gianni root' } },
      gate: { kind: 'security', label: 'HELLO principal seam', status: 'enforced', note: 'Key-signed session: the operator hosts it but never touches identity — the cert chains to the USER root.' },
      note: 'Session placement is the third, tiny discovery question — answered by plain web bootstrap, deliberately before glade machinery starts.',
      docRef: `${WD} §7b · ${AZ} §7b`,
      sets: { dc1: { 'session gryth1': 'open (key-signed, roaming)' } },
    },
    {
      state: 'S7', phase: 'RM1', kind: 'internal', from: 'dc1', frame: 'ROUTE',
      label: 'plug verifies the device chain',
      payload: { detail: { plug: 'device certs', check: 'cert → gianni root', bind: 'principal: gianni (key-signed)' } },
      gate: { kind: 'security', label: 'trust-plug principal bind', status: 'enforced', note: 'Which authn methods are acceptable is GIANNI’s replicated policy, not operator config (GDL-033).' },
      note: 'Full cryptographic self — contrast s-idp’s operator-vouched bind.',
      docRef: `${AZ} §7b`,
    },
    {
      state: 'A3', phase: 'RM2', kind: 'message', from: 'gryth1', to: 'dc1', frame: 'SUBSCRIBE',
      label: 'subscribe: workspace directory',
      payload: { share: 'home', gladeId: 'dir.workspaces', key: '∅ (unkeyed)', shape: 'log' },
      note: 'Same first ask as ever — the entry node happens to be far from home.',
      sets: { dc1: { 'sub home/dir.workspaces': 'gryth1' } },
    },
    {
      state: 'A4', phase: 'RM2', kind: 'internal', from: 'dc1', frame: 'FOLD',
      label: 'fold the operator-held replica',
      payload: { share: 'home', detail: { source: 'durable home-node role — replica.hold granted at signup' } },
      note: 'No p2p hop for the list: the DC fleet was ALREADY a replica because gianni placed it there, as policy.',
      docRef: `${WD} §7b (ladder) · ${AZ} §7a`,
    },
    {
      state: 'A5', phase: 'RM2', kind: 'message', from: 'dc1', to: 'gryth1', frame: 'OPS',
      label: 'the list, instantly', response: true,
      payload: { share: 'home', gladeId: 'dir.workspaces', shape: 'log', detail: { ops: '6 WorkspaceEntry + claims' } },
      note: 'Directory latency at the café = one hop to the fleet.',
      sets: { gryth1: { view: '6 workspaces (via dc1)' } },
    },
    {
      state: 'C1', phase: 'RM3', kind: 'message', from: 'gryth1', to: 'dc1', frame: 'SUBSCRIBE',
      label: 'subscribe: workspace tree',
      payload: { share: 'ws-razel', gladeId: 'ws.tree', key: '{root:"/src"}', shape: 'value' },
      note: 'The workspace lives on the personal node at home.',
      sets: { gryth1: { subs: 'ws-razel/ws.tree{/src}' } },
    },
    {
      state: 'S4', phase: 'RM3', kind: 'internal', from: 'dc1', frame: 'ROUTE',
      label: 'check(): ALLOW (gianni’s grant)',
      payload: { share: 'ws-razel', detail: { verdict: 'ALLOW', basis: 'read.* ∈ grant(gianni, ws-razel)' } },
      gate: { kind: 'capability', label: 'fan-out capability check', status: 'enforced', note: 'Papers, not face: the chain rides the session; the fold answers.' },
      note: 'User authorization — one axis.',
      docRef: `${AZ} §6`,
      sets: { dc1: { 'sub ws-razel/ws.tree': 'gryth1' } },
    },
    {
      state: 'S8', phase: 'RM3', kind: 'internal', from: 'dc1', frame: 'ROUTE',
      label: 'placement check: WARM replica',
      payload: { share: 'ws-razel', detail: { question: 'may saas-corp hold ws-razel plaintext?', answer: 'YES — hold granted to saas-corp', consequence: 'dc1 becomes a warm replica; café reads are local' } },
      gate: { kind: 'capability', label: 'placement (replica.hold)', status: 'enforced', note: 'The OTHER axis: node trust = operator relation. Same protocol node, different trust binding — the performance tier IS the trust tier.' },
      note: 'The owner granted replica.hold to the operator, so the entry node may store and serve this share.',
      docRef: `${AZ} §7a`,
    },
    {
      state: 'C2', phase: 'RM3', kind: 'internal', from: 'dc1', frame: 'ROUTE',
      label: 'route to claim-holder',
      payload: { share: 'ws-razel', detail: { answer: 'local1 (personal node) — epoch 2 valid' } },
      gate: { kind: 'routing', label: 'ServeClaim lookup', status: 'designed', note: 'Service discovery = a fold over the directory. Unchanged by roaming.' },
      note: 'WHO serves: the directory. WHERE it is: iroh, next.',
      docRef: `${WD} §7b`,
      sets: { dc1: { 'route ws-razel': 'local1 (personal)' } },
    },
    {
      state: 'B4', phase: 'RM3', kind: 'message', from: 'dc1', to: 'iroh', frame: 'RESOLVE',
      label: 'resolve the personal node',
      payload: { detail: { nodeId: 'local1 (ed25519)' } },
      note: 'Node discovery: self-certifying — the name IS the key; publication is signed by it.',
      docRef: `${WD} §7b (layers)`,
    },
    {
      state: 'B5', phase: 'RM3', kind: 'message', from: 'iroh', to: 'dc1', frame: 'ADDR',
      label: 'relay path (NAT at home)', response: true,
      payload: { detail: { addr: 'relay path — no direct route' } },
      note: 'Poisoned hints would fail the dial handshake — DoS at worst, never impersonation.',
    },
    {
      state: 'B6', phase: 'RM3', kind: 'message', from: 'dc1', to: 'local1', frame: 'DIAL',
      label: 'dial home',
      payload: { detail: { transport: 'iroh QUIC via relay', session: 'node↔node' } },
      gate: { kind: 'security', label: 'node↔node HELLO seam', status: 'enforced', note: 'Operator chains verify both ways: gianni’s node knows it is talking to saas-corp’s fleet, and vice versa.' },
      note: 'The personal node never interactively auths gianni — it verifies chains.',
      docRef: `${AZ} §7b`,
      sets: { dc1: { links: 'local1 (relay)' }, local1: { links: 'dc1 (relay)' } },
    },
    {
      state: 'C3', phase: 'RM3', kind: 'message', from: 'dc1', to: 'local1', frame: 'SUBSCRIBE',
      label: 'forward interest home',
      payload: { share: 'ws-razel', gladeId: 'ws.tree', key: '{root:"/src"}', shape: 'value' },
      gate: { kind: 'capability', label: 'capability check', status: 'enforced', note: 'Every hop re-verifies from its OWN fold — the personal node checks gianni’s chain again.' },
      note: 'Enforcement at every hop survives roaming untouched.',
      docRef: `${AZ} §6`,
      sets: { local1: { 'sub ws-razel/ws.tree': 'dc1 (for gryth1)' } },
    },
    {
      state: 'C5', phase: 'RM3', kind: 'message', from: 'local1', to: 'dc1', frame: 'OPS',
      label: 'tree ships to the warm replica', response: true,
      payload: { share: 'ws-razel', gladeId: 'ws.tree', shape: 'value' },
      note: 'dc1 stores it (placement granted) — subsequent reads and windows are one café hop.',
      sets: { dc1: { 'replica ws-razel': 'warm (via local1)' } },
    },
    {
      state: 'C6', phase: 'RM3', kind: 'message', from: 'dc1', to: 'gryth1', frame: 'OPS',
      label: 'snappy at the café', response: true,
      payload: { share: 'ws-razel', gladeId: 'ws.tree', shape: 'value' },
      note: 'INV-4 (grant) and INV-5 (placement) both hold at this serve — mechanically checked.',
      sets: { gryth1: { view: '6 workspaces + /src tree' } },
    },
    {
      state: 'C1', phase: 'RM4', kind: 'message', from: 'gryth1', to: 'dc1', frame: 'SUBSCRIBE',
      label: 'subscribe: the sensitive share',
      payload: { share: 'ws-secret', gladeId: 'ws.tree', key: '{root:"/"}', shape: 'value' },
      note: 'Same user, full grant — different share policy.',
    },
    {
      state: 'S4', phase: 'RM4', kind: 'internal', from: 'dc1', frame: 'ROUTE',
      label: 'check(): ALLOW (owner)',
      payload: { share: 'ws-secret', detail: { verdict: 'ALLOW — gianni owns it' } },
      gate: { kind: 'capability', label: 'fan-out capability check', status: 'enforced', note: 'User axis passes.' },
      note: 'Authorization is not the constraint here.',
      docRef: `${AZ} §6`,
      sets: { dc1: { 'sub ws-secret/ws.tree': 'gryth1' } },
    },
    {
      state: 'S8', phase: 'RM4', kind: 'internal', from: 'dc1', frame: 'ROUTE', variant: 'a',
      variantNote: 'Placement DENIED: hold(ws-secret) names gianni only — the entry node degrades to a blind pipe (forward, never store).',
      label: 'placement check: BLIND PIPE',
      payload: { share: 'ws-secret', detail: { question: 'may saas-corp hold ws-secret plaintext?', answer: 'NO — hold: gianni only', consequence: 'relay-only: every read rides home; nothing persists here' } },
      gate: { kind: 'capability', label: 'placement (replica.hold)', status: 'enforced', note: 'The owner chose slow-but-private for this share — the tier is data, visible, and the owner’s own.' },
      note: 'dc1 forwards frames without storing ops. Note what does NOT appear in dc1’s state: no `replica ws-secret` key — INV-5 would flag it.',
      docRef: `${AZ} §7a/§7b`,
    },
    {
      state: 'C3', phase: 'RM4', kind: 'message', from: 'dc1', to: 'local1', frame: 'SUBSCRIBE',
      label: 'forward-only interest',
      payload: { share: 'ws-secret', gladeId: 'ws.tree', key: '{root:"/"}', shape: 'value', detail: { mode: 'relay (no store)' } },
      gate: { kind: 'capability', label: 'capability check', status: 'enforced', note: 'The origin still verifies the user chain.' },
      note: 'The pipe is blind but the ends are not.',
      docRef: `${AZ} §6`,
      sets: { local1: { 'sub ws-secret/ws.tree': 'dc1 (relay for gryth1)' } },
    },
    {
      state: 'C5', phase: 'RM4', kind: 'message', from: 'local1', to: 'dc1', frame: 'OPS',
      label: 'ops transit (not stored)', response: true,
      payload: { share: 'ws-secret', gladeId: 'ws.tree', detail: { transit: 'forwarded, never persisted at dc1' } },
      note: 'Op integrity is end-to-end (chains + signatures) — a blind node can withhold, never forge.',
      docRef: `${AZ} §7a (integrity)`,
    },
    {
      state: 'C6', phase: 'RM4', kind: 'message', from: 'dc1', to: 'gryth1', frame: 'OPS',
      label: 'slower, by choice', response: true,
      payload: { share: 'ws-secret', gladeId: 'ws.tree', shape: 'value' },
      note: 'Every ws-secret read rides the relay home. The café experience differs per share because the OWNER’s placement policy differs per share.',
      sets: { gryth1: { view: '… + ws-secret (slow path, private)' } },
    },
  ],
};

export const S_TENANT: Scenario = {
  id: 's-tenant',
  stage: 2,
  title: 'Multi-tenant DC — two roots, one node',
  summary: 'gianni and a teammate share a SaaS-hosted workspace on one DC node. Colocation works because BOTH accepted the operator — that acceptance is why the DC node is cheap.',

  actors: pick('gryth1', 'guest1', 'dc1'),

  initial: {
    gryth1: { device: 'gianni’s laptop (device cert)' },
    guest1: { device: 'teammate’s laptop (cert → guest root)' },
    dc1: {
      operator: 'saas-corp',
      'claim ws-team': 'held — epoch 1',
      serving: 'ws-team via grazel (SaaS-hosted)',
      'replica ws-team': 'origin',
      'hold ws-team': 'granted: saas-corp (by both members at share creation)',
      'grant gryth1 ws-team': 'read.*, write.append, gwz.*',
      'grant guest1 ws-team': 'read.*, write.append',
      trust: 'plug: device certs',
    },
  },

  phases: [
    { id: 'TN1', label: 'Two roots arrive', summary: 'Different user roots, same entry node.' },
    { id: 'TN2', label: 'Colocated serving', summary: 'One replica, two sessions, per-session verdicts.' },
    { id: 'TN3', label: 'Live collaboration', summary: 'A write fans out across trust roots — through the operator both accepted.' },
  ],

  steps: [
    {
      state: 'A1', phase: 'TN1', kind: 'message', from: 'gryth1', to: 'dc1', frame: 'HELLO',
      label: 'gianni’s session',
      payload: { detail: { deviceCert: 'chains to gianni root' } },
      gate: { kind: 'security', label: 'HELLO principal seam', status: 'enforced', note: 'Key-signed.' },
      note: 'Root one.',
      docRef: `${AZ} §7b`,
      sets: { dc1: { 'session gryth1': 'open (gianni root)' } },
    },
    {
      state: 'A1', phase: 'TN1', kind: 'message', from: 'guest1', to: 'dc1', frame: 'HELLO',
      label: 'teammate’s session',
      payload: { detail: { deviceCert: 'chains to guest root' } },
      gate: { kind: 'security', label: 'HELLO principal seam', status: 'enforced', note: 'Key-signed, DIFFERENT root — no relationship to gianni required.' },
      note: 'Root two. Neither user trusts the other’s hardware; both trust the operator. That asymmetry is the entire multi-tenant model.',
      docRef: `${AZ} §7a`,
      sets: { dc1: { 'session guest1': 'open (guest root)' } },
    },
    {
      state: 'C1', phase: 'TN2', kind: 'message', from: 'gryth1', to: 'dc1', frame: 'SUBSCRIBE',
      label: 'gianni subscribes',
      payload: { share: 'ws-team', gladeId: 'ws.tree', key: '{root:"/"}', shape: 'value' },
      note: 'The workspace lives HERE — SaaS-hosted origin.',
      sets: { gryth1: { subs: 'ws-team/ws.tree' } },
    },
    {
      state: 'S4', phase: 'TN2', kind: 'internal', from: 'dc1', frame: 'ROUTE',
      label: 'check() for gianni: ALLOW',
      payload: { share: 'ws-team', detail: { verdict: 'ALLOW (read.*)' } },
      gate: { kind: 'capability', label: 'fan-out capability check', status: 'enforced', note: 'Per-session verdicts against one fold.' },
      note: 'Session one admitted to the stream.',
      docRef: `${AZ} §6`,
      sets: { dc1: { 'sub ws-team/ws.tree': 'gryth1' } },
    },
    {
      state: 'A5', phase: 'TN2', kind: 'message', from: 'dc1', to: 'gryth1', frame: 'OPS',
      label: 'served from origin', response: true,
      payload: { share: 'ws-team', gladeId: 'ws.tree', shape: 'value' },
      note: 'INV-4/INV-5 both hold: grant present, placement granted by both members.',
      sets: { gryth1: { view: 'ws-team tree (live)' } },
    },
    {
      state: 'C1', phase: 'TN2', kind: 'message', from: 'guest1', to: 'dc1', frame: 'SUBSCRIBE',
      label: 'teammate subscribes',
      payload: { share: 'ws-team', gladeId: 'ws.tree', key: '{root:"/"}', shape: 'value' },
      note: 'Same stream, other root.',
      sets: { guest1: { subs: 'ws-team/ws.tree' } },
    },
    {
      state: 'F1', phase: 'TN2', kind: 'internal', from: 'dc1', frame: 'ROUTE',
      label: 'attach to the replicated stream',
      payload: { share: 'ws-team', detail: { found: 'origin here — add session' } },
      gate: { kind: 'routing', label: 'replica-attach', status: 'designed', note: 'The s-fanout mechanics, across trust roots.' },
      note: 'One copy of the data, N sessions.',
      docRef: 's-fanout F1',
    },
    {
      state: 'S4', phase: 'TN2', kind: 'internal', from: 'dc1', frame: 'ROUTE',
      label: 'check() for teammate: ALLOW',
      payload: { share: 'ws-team', detail: { verdict: 'ALLOW (read.*)', basis: 'guest’s own grant — not gianni’s' } },
      gate: { kind: 'capability', label: 'fan-out capability check', status: 'enforced', note: 'Cached ≠ allowed still runs — it just passes for this principal.' },
      note: 'Colocation without cross-trust: each session stands on its own grant.',
      docRef: `${AZ} §7a`,
      sets: { dc1: { 'sub ws-team/ws.tree': 'gryth1, guest1' } },
    },
    {
      state: 'A5', phase: 'TN2', kind: 'message', from: 'dc1', to: 'guest1', frame: 'OPS',
      label: 'teammate served', response: true,
      payload: { share: 'ws-team', gladeId: 'ws.tree', shape: 'value' },
      note: 'Two roots reading one replica on hardware neither owns — because both accepted saas-corp.',
      sets: { guest1: { view: 'ws-team tree (live)' } },
    },
    {
      state: 'J3', phase: 'TN3', kind: 'message', from: 'gryth1', to: 'dc1', frame: 'APPEND',
      label: 'gianni edits',
      payload: { share: 'ws-team', gladeId: 'ws.tree', detail: { op: 'file added (origin: gryth1)' } },
      note: 'write.append is in gianni’s grant; the accepting hop checks it like any verb.',
      docRef: `${AZ} §1 (writes)`,
      sets: { dc1: { 'replica ws-team': 'origin (+1 op)' } },
    },
    {
      state: 'B9', phase: 'TN3', kind: 'message', from: 'dc1', to: 'guest1', frame: 'OPS',
      label: 'fan-out across roots', response: true,
      payload: { share: 'ws-team', gladeId: 'ws.tree' },
      note: 'The collaboration hop: one user’s op reaches another user’s session through the operator both accepted. This is the SaaS product, drawn.',
      sets: { guest1: { view: 'ws-team tree (updated by gianni)' } },
    },
  ],
};

export const S_LOCAL_GUEST: Scenario = {
  id: 's-local-guest',
  stage: 2,
  title: 'Guest on a personal node — directional exposure',
  summary: 'My data may flow to a guest THROUGH my node (no new exposure). The guest’s private share refuses placement on my hardware — the same rule, pointed the other way.',

  actors: pick('guest1', 'local1', 'peer1'),

  initial: {
    guest1: { device: 'teammate’s session (guest root)', 'local cache': 'own device replica of ws-gpriv' },
    local1: {
      operator: 'gianni',
      'session guest1': 'open (guest root, admitted)',
      'replica ws-secret': 'origin (gianni’s data)',
      'hold ws-secret': 'granted: gianni',
      'claim ws-secret': 'held — epoch 1',
      'grant guest1 ws-secret': 'read.subscribe (from s-grant)',
      'sub home': 'peer1 (mesh)',
    },
    peer1: { operator: 'gianni', 'sub home': 'local1 (mesh)' },
  },

  phases: [
    { id: 'LG1', label: 'My data to the guest', summary: 'Granted read through my node: the plaintext was already mine.' },
    { id: 'LG2', label: 'The guest’s data, refused', summary: 'Their private share will not land on hardware whose operator they never accepted.' },
  ],

  steps: [
    {
      state: 'C1', phase: 'LG1', kind: 'message', from: 'guest1', to: 'local1', frame: 'SUBSCRIBE',
      label: 'guest reads my workspace',
      payload: { share: 'ws-secret', gladeId: 'ws.tree', key: '{root:"/"}', shape: 'value' },
      note: 'The s-grant ceremony already ran; the guest holds read.subscribe.',
      sets: { guest1: { subs: 'ws-secret/ws.tree' } },
    },
    {
      state: 'S4', phase: 'LG1', kind: 'internal', from: 'local1', frame: 'ROUTE',
      label: 'check(): ALLOW',
      payload: { share: 'ws-secret', detail: { verdict: 'ALLOW', exposure: 'NONE new — the operator (gianni) owns this plaintext already' } },
      gate: { kind: 'capability', label: 'fan-out capability check', status: 'enforced', note: 'The directional rule: serving MY data through MY node to a granted guest adds zero exposure.' },
      note: 'Cross-user serving on a personal node is fine in this direction.',
      docRef: `${AZ} §7a`,
      sets: { local1: { 'sub ws-secret/ws.tree': 'guest1' } },
    },
    {
      state: 'A5', phase: 'LG1', kind: 'message', from: 'local1', to: 'guest1', frame: 'OPS',
      label: 'served', response: true,
      payload: { share: 'ws-secret', gladeId: 'ws.tree', shape: 'value' },
      note: 'INV-4: guest’s grant is in the fold. INV-5: gianni holds his own share. Both green.',
      sets: { guest1: { view: 'ws-secret tree (live)' } },
    },
    {
      state: 'C1', phase: 'LG2', kind: 'message', from: 'guest1', to: 'local1', frame: 'SUBSCRIBE',
      label: 'guest asks MY node for THEIR private share',
      payload: { share: 'ws-gpriv', gladeId: 'ws.tree', key: '{root:"/"}', shape: 'value' },
      note: 'Convenient for the guest — their session is here. But serving requires replicating…',
      sets: { guest1: { subs: 'ws-secret/ws.tree + ws-gpriv (requested)' } },
    },
    {
      state: 'S8', phase: 'LG2', kind: 'internal', from: 'local1', frame: 'ROUTE', variant: 'a',
      variantNote: 'Placement DENIED on the serving node itself: hold(ws-gpriv) does not name operator gianni — the guest never accepted my hardware for their plaintext.',
      label: 'placement check: REFUSED',
      payload: { share: 'ws-gpriv', detail: { question: 'may operator gianni hold ws-gpriv plaintext?', answer: 'NO — hold: guest-root only', consequence: 'no replica here; relay-only possible via a node the guest accepts' } },
      gate: { kind: 'capability', label: 'placement (replica.hold)', status: 'enforced', note: 'The same rule as s-roam’s blind pipe, pointed the other way. Note local1’s state: no `replica ws-gpriv` key ever appears — INV-5 would flag it.' },
      note: 'This is the answer to "should a local peer share data between users": yes for data its operator owns, never by silently hosting data its operator was not accepted for.',
      docRef: `${AZ} §7a`,
      sets: { local1: { 'denied placement ws-gpriv': 'operator not in hold set' } },
    },
    {
      state: 'S3', phase: 'LG2', kind: 'message', from: 'local1', to: 'guest1', frame: 'STATUS',
      label: 'refused with the honest reason', response: true,
      payload: { share: 'ws-gpriv', detail: { result: 'placement refused', reason: 'this node’s operator is not accepted for your share', remedy: 'use your own device replica, or grant replica.hold to operator gianni' } },
      gate: { kind: 'security', label: 'enforcement cut', status: 'enforced', note: 'The remedy names the guest’s actual choices — including extending trust to this operator, which is s-grant’s ceremony aimed at a node.' },
      note: 'The guest’s own device replica still works (their `local cache` state — untouched). Nothing is lost; nothing leaked.',
      docRef: `${AZ} §7a · ${WD} §7b`,
      sets: { guest1: { view: 'ws-gpriv: use own replica (placement refused here)', subs: 'ws-secret/ws.tree' } },
    },
  ],
};
